### ISSUE TITLE
RTC, light sensor - burned luacontroler, and error in log with lcd

### ISSUE THREAD

**Issue by raptikCZ** [Jeija/minetest-mod-digilines#24]
HI, 
i have this behavior of RTC and light sensor:
both of them causes burned luacontoler when i try to get status from them. it not depends on code. 
i can just type:
 digiline_send("sensor","GET")

and got burned lua controller - same when used on interupt(1)

strange is that, if write code for something else after this line - controller do that, but it is like it will be burned in next repetion of code.

in debug.txt is nothing about this - no error, warning...

only this i have in debug.txt:

10:01:11: ACTION[ServerThread]: Deprecated call to "get_entity_name
10:01:11: ACTION[ServerThread]: stack traceback:
10:01:11: ACTION[ServerThread]:         [C]: in function 'get_entity_name'
10:01:11: ACTION[ServerThread]:         .../dalibor/.minetest/mods/digilines/digilines_lcd/init.lua:42: in function 'clearscreen'
10:01:11: ACTION[ServerThread]:         .../dalibor/.minetest/mods/digilines/digilines_lcd/init.lua:67: in function 'action'
10:01:11: ACTION[ServerThread]:         .../dalibor/.minetest/mods/digilines/digilines/internal.lua:80: in function 'transmit'
10:01:11: ACTION[ServerThread]:         .../dalibor/.minetest/mods/digilines/digilines/internal.lua:88: in function 'transmit'
10:01:11: ACTION[ServerThread]:         /home/dalibor/.minetest/mods/digilines/digilines/init.lua:13: in function 'receptor_send'
10:01:11: ACTION[ServerThread]:         ...e/dalibor/.minetest/mods/mesecons_luacontroller/init.lua:242: in function 'func'
10:01:11: ACTION[ServerThread]:         /usr/share/minetest/builtin/game/misc.lua:19: in function </usr/share/minetest/builtin/game/misc.lua:9>
10:01:11: ACTION[ServerThread]:         /usr/share/minetest/builtin/game/register.lua:348: in function </usr/share/minetest/builtin/game/register
.lua:336>

but LCD working fine...

i heve it on ubuntu 14.04, minetest 0.4.11 (same is on 0.4.10)

is it possible, that i can broke it with adding recipe only for light sensor? but i dont think, that it can broke different code in RTC

**Comment by Jeija** [comment]
That behaviour is perfectly fine. What is happening is that the `GET` message goes across the digiline and the RTC answers. The luacontroller receives that anwer. Every time the luacontroller receives an answer the code is executed again. In your case, that makes the luacontroller send the `GET` signal again. Do you see where this leads? It creates an endless loop of the RTC responding and the luacontroller asking again.

Instead, you could use this code (tested with an RTC on channel "rtc"):
```Lua
if (event.type ~= "digiline") then
  digiline_send("rtc", "GET")
else
  print("Time from RTC: " .. event.msg)
end
```

**Comment by raptikCZ** [comment]
ok, thats i need  - endless loop and it is normal in normal life like in PLC :) but i didnt expect burning of luacontroler here :) in normal world, you cant burn your cpu by this because you are limited by bus speed, cpu clock etc and communication libraries are mostly adjusted for this...

i trying to automate lighting of house in my minetest (before i have it with standart solar panel)

then it is not problem of digilines,but code is runing too fast when i just send get and read answer.
 i tried it to send get, check digilines and set port of luacontr. - but it burned too and i didnt find any wait or delay function in lua lang. (but must admit that i forgot to make same with for)

but your code worked and after this i have periodic run:
(your code runs only once)

interrupt(1,"svetlo")
if (event.type ~= "digiline" ) then
 digiline_send("sensor", "GET")
else
 digiline_send("scrn1" , "light " ..  event.msg .. " level")
end

thanks for help, and i must little learn about luacontroler :)

**Comment by ssieb** [comment]
You don't want that either.  The interrupt line will be executed on every trigger, so they will pile up.  You only want one interrupt delay at a time.  Look at the different event.type options.
